# Generated by Django 5.0.3 on 2024-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="link",
            name="project",
        ),
        migrations.RemoveField(
            model_name="technology",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="links",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="portfolio.link"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="portfolio.technology"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=250),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="portfolio_p_created_6dcf92_idx"
            ),
        ),
    ]
