# Generated by Django 5.0.3 on 2024-03-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_options_remove_link_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technology",
            name="url",
        ),
    ]
