# Generated by Django 5.0.3 on 2024-04-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_project_links_link_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.TextField(blank=True),
        ),
    ]
