# Generated by Django 5.0.3 on 2024-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_link_icon_alter_technology_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=models.ImageField(blank=True, upload_to="icon/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.ImageField(blank=True, upload_to="icon/%Y/%m/%d"),
        ),
    ]
