# Generated by Django 5.0.3 on 2024-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_link_icon_alter_project_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=models.ImageField(blank=True, upload_to="icon/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, upload_to="portfolio/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.ImageField(blank=True, upload_to="icon/%Y/%m/%d"),
        ),
    ]
