# Generated by Django 5.0.3 on 2024-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_project_demo_project_github"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="demo",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
