# Generated by Django 5.0.3 on 2024-04-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_project_demo_alter_project_github_delete_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("the_year", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="portfolio_e_created_95c7d8_idx"
                    )
                ],
            },
        ),
    ]
