# Generated by Django 5.0.3 on 2024-04-25 21:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
