# Generated by Django 5.0.3 on 2024-04-30 16:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_information_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
